name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install Yarn
        run: npm i -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Build components
        run: yarn workspace sid build
      - name: Build dashboard
        run: yarn workspace dashboard build
      - name: Deploy examples
        uses: maxheld83/ghpages@v0.3.0
        env:
          BUILD_DIR: packages/dashboard/dist
          GH_PAT: ${{ secrets.GH_PAT }}
